name: Offline Orator Testing Action

on:
  workflow_dispatch: # Allows manual trigger testing
  schedule:
    - cron: '0 13 * * *' # Bypasses to run exactly at 8:00 AM EST every day

jobs:
  run-orator:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install System Dependencies (FFmpeg)
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: Install Python Dependencies
        run: pip install -r requirements.txt

      - name: Execute Orator Offline Trigger
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          SPOTIPY_CLIENT_ID: ${{ secrets.SPOTIPY_CLIENT_ID }}
          SPOTIPY_CLIENT_SECRET: ${{ secrets.SPOTIPY_CLIENT_SECRET }}
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: python main.py --action
